### PR TITLE
OM-46: allow to login with mPass

### PR DESCRIPTION
**Pull request by jdolkowski**
https://openimis.atlassian.net/browse/OM-46

Changes:
- Display MPass provider instead of credentials (configurable).
- Enable login with MPass.

Peek 2023-10-17 13-38

### CODE REVIEW

**Comment by olewandowski1** [comment]
Could you do a review? @jdolkowski @sniedzielski

**Review by jdolkowski — COMMENTED** [review]
Looks good to me.

**Comment by sniedzielski** [comment]
Two hotspots marked as safe due to fact that 'password' reffers to the label, not credential.

**Review by sniedzielski — APPROVED** [review]

**Comment by olewandowski1** [comment]
@jdolkowski If I'm not mistaken this is related to this svgr library, but I was not implementing that. @jdolkowski Could you please elaborate if I'm wrong?

**Comment by jdolkowski** [comment]
Exactly, it had to be added to be allowed to add svg files. However I am not sure if bundle.js in core could have been used instead of adding it in the module. This could be checked.

**Review by dborowiecki — APPROVED** [review]

**Pull request merged**
